### ISSUE TITLE
How to be a nit-picker in 5 easy steps

### ISSUE THREAD

**Issue by CamiloMM** [scottcorgan/zip-object#1]
### Step one:
- [x] Be a lazy ass and google for something that is so ridiculously simple you should be ashamed of not rubbing your own neurons together to write your own function.

![google](https://cloud.githubusercontent.com/assets/2404138/5631171/889fd026-95ab-11e4-898a-2b1879f66336.jpg)
### Step two:
- [x] Look at the source, noticing every step like a baby that looks at an adult walking and spends some time trying to figure out how they're doing it.

![baby](https://cloud.githubusercontent.com/assets/2404138/5631166/7788f0ce-95ab-11e4-83f2-126dbeda479c.jpg)
### Step three:
- [x] When your two neurons finally fire up, be arrogant enough to look in disdain at what is a stylistic code choice, since it does not match your religion on operators and whatnot

![c-bible](https://cloud.githubusercontent.com/assets/2404138/5631121/1fd4fd5a-95ab-11e4-8ced-b4a4c68cea45.jpg)
### Step four:
- [x] File an issue about how on [line 10](https://github.com/scottcorgan/zip-object/blob/master/index.js#L10) this guy does  

``` js
for (i; i < keys.length; i += 1) {
```

instead of  

``` js
for (; i < keys.length; i++) {
```

(or inlining the `var i = 0` in the `for`)

![pauly-d](https://cloud.githubusercontent.com/assets/2404138/5631300/a04bdf98-95ac-11e4-9814-54aa26482aef.jpg)
### Step five
- [ ] <sub><sup>Send a pull request</sup></sub>

![thanks-obama](https://cloud.githubusercontent.com/assets/2404138/5631425/97071dfc-95ad-11e4-9c46-01ecc8da729b.jpg)

**Comment by scottcorgan** [comment]
Not sure I follow.

**Comment by CamiloMM** [comment]
I was sleepy, lazy, and found it so weird how in your code you `i += 1` instead of `i++` and `i;` when you don't need to.

Not really an issue, just wanted to point out how weird that line looks. Disconsider :)
